# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-23 14:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('change_date', models.DateTimeField(auto_now=True, null=True)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('father_name', models.CharField(blank=True, max_length=128, null=True)),
                ('birthday', models.DateField()),
                ('phone_number', models.CharField(max_length=32)),
                ('passport_num', models.CharField(max_length=11, unique=True)),
                ('scor_ball', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inn', models.CharField(max_length=12, unique=True)),
                ('contr_name', models.CharField(max_length=256)),
                ('address', models.CharField(max_length=1024)),
                ('contr_type', models.CharField(choices=[(b'b', b'\xd0\x9a\xd1\x80\xd0\xb5\xd0\xb4\xd0\xb8\xd1\x82\xd0\xbd\xd0\xb0\xd1\x8f \xd0\xbe\xd1\x80\xd0\xb3\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb7\xd0\xb0\xd1\x86\xd0\xb8\xd1\x8f'), (b'p', b'\xd0\x9f\xd0\xb0\xd1\x80\xd1\x82\xd0\xbd\xd0\xb5\xd1\x80')], max_length=1)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('post_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[(b'0', b'\xd0\x9d\xd0\xbe\xd0\xb2\xd0\xb0\xd1\x8f'), (b'1', b'\xd0\x9e\xd1\x82\xd0\xbf\xd1\x80\xd0\xb0\xd0\xb2\xd0\xbb\xd0\xb5\xd0\xbd\xd0\xb0'), (b'2', b'\xd0\x9f\xd0\xbe\xd0\xbb\xd1\x83\xd1\x87\xd0\xb5\xd0\xbd\xd0\xb0'), (b'3', b'\xd0\x9e\xd0\xb4\xd0\xbe\xd0\xb1\xd1\x80\xd0\xb5\xd0\xbd\xd0\xbe'), (b'4', b'\xd0\x9e\xd1\x82\xd0\xba\xd0\xb0\xd0\xb7\xd0\xb0\xd0\xbd\xd0\xbe'), (b'5', b'\xd0\x92\xd1\x8b\xd0\xb4\xd0\xb0\xd0\xbd\xd0\xbe')], default=b'0', max_length=1)),
                ('client_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credit.ClientProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('change_date', models.DateTimeField(auto_now=True, null=True)),
                ('start_rotation_date', models.DateTimeField(blank=True, null=True)),
                ('stop_rotation_date', models.DateTimeField(blank=True, null=True)),
                ('proposal_name', models.CharField(max_length=256)),
                ('proposal_type', models.CharField(choices=[(b'c', b'\xd0\x9f\xd0\xbe\xd1\x82\xd1\x80\xd0\xb5\xd0\xb1'), (b'm', b'\xd0\x98\xd0\xbf\xd0\xbe\xd1\x82\xd0\xb5\xd0\xba\xd0\xb0'), (b'a', b'\xd0\x90\xd0\xb2\xd1\x82\xd0\xbe\xd0\xba\xd1\x80\xd0\xb5\xd0\xb4\xd0\xb8\xd1\x82')], max_length=1)),
                ('min_scor_ball', models.PositiveIntegerField(default=1)),
                ('max_scor_ball', models.PositiveIntegerField(default=1)),
                ('credit_contr', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='credit.Contractor')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='credit.Proposal'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='partner_contr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='credit.Contractor'),
        ),
    ]
